### ISSUE TITLE
Monitoring Jiralert

### ISSUE THREAD

**Issue by bumarcell** [prometheus-community/jiralert#102]
Hello everybody,
I wanted to ask of there's an (out of the box) way to monitor Jiralert and trigger a webhook for example once it's down?

Best regards

**Comment by nvtkaszpir** [comment]
https://grafana.com/grafana/dashboards/10769
you could create corresponding rules for prometheus, for example.

**Comment by bumarcell** [comment]
Any idea how to let this metric be exported?

**Comment by nvtkaszpir** [comment]
Depends on how you host jiralert.
Jiralert itself exposes metrics on port 9097 under /metrics path, which are in prometheus format.
So if you are able to scrape that metrics with prometheus then it's just very easy to add alerting on top of that, for example with blackbox-exporter.

**Comment by bumarcell** [comment]
Perfect. Many thanks 🙏
