### ISSUE TITLE
Proposal: Move to Alertmanager.

### ISSUE THREAD

**Issue by bwplotka** [prometheus-community/jiralert#145]
Given the popularity and use, I would like to propose pushing this code to Alertmanager [notify](https://github.com/prometheus/alertmanager/tree/main/notify) package. 

I got information AM maintainers will consider this (: 

We need, however, maintainer for this notifier. Any volunteers? (:

**Comment by bwplotka** [comment]
We also need official maintainer. I can co-maintain, but we need someone else to own this, so looking for volunteers (:

**Comment by twotired** [comment]
@bwplotka What's involved with being the maintainer? I'm open to being co-maintainer at least.

**Comment by bwplotka** [comment]
Just a general review of related PRs, issues and security fixes (: 

Thanks, noted! Are you on the cncf slack?

**Comment by twotired** [comment]
I am there, in the #jiralert channel

**Comment by bwplotka** [comment]
Amazing thanks! I think we have nice collection of contributors to attempt the move. **Any of you would have time to prepare a PR to Alertmanager?** I can even create feature branch for us. We can then together work towards PR with jiralert plugin in https://github.com/prometheus/alertmanager as well as documentation (: I will be there to consult and review (together with Alertmanager maintainers e.g. @simonpasquier)

**Comment by twotired** [comment]
I was a little confused by what's needed here. I thought there was a need for additional maintainers of this project so that there could be a greater capacity to review and approve PRs and create new releases. Is that not in consideration?

I would be open to helping with the migration, but right now the priority for my team is to get some of the fixes in PRs into a new release. It is especially painful when we keep hitting the 32KB limit and JIRAs cannot be updated.

**Comment by bwplotka** [comment]
Sorry for confusion, but as description suggests (https://github.com/prometheus-community/jiralert/issues/145#issue-1508084656) this issue is about proposing it to Alertmanager and maintaining similar code (with the same functionality) there (: 

> but right now the priority for my team is to get some of the fixes in PRs into a new release. It is especially painful when we keep hitting the 32KB limit and JIRAs cannot be updated.

Yup, feel free to propose changes to this repo for now. Whatever we do here will be useful in Alertmanager 👍🏽

**Comment by jkroepke** [comment]
I've setup an PR on alertmanager #3590

**Comment by jkroepke** [comment]
The PR is merged on AM site.

**Comment by k0ste** [comment]
The support [JIRA API in Alertmanager](https://prometheus.io/docs/alerting/latest/configuration/#jira_config) available since release v[0.28.0](https://github.com/prometheus/alertmanager/releases/tag/v0.28.0) 🎈

**Comment by SuperQ** [comment]
**This project has been deprecated in favor of [direct alertmanager integration](https://prometheus.io/docs/alerting/latest/configuration/#jira_config).**
