### ISSUE TITLE
Build Docke image error

### ISSUE THREAD

**Issue by JetSquirrel** [prometheus-community/jiralert#172]
I try to build docker image, but there is an error:
```
....
#10 0.319 Please ensure you are using go version go1.19.12 linux/amd64 for formatting code.
#10 0.319 make: *** [Makefile.common:126: common-style] Error 1
------
executor failed running [/bin/sh -c GO111MODULE=on GOBIN=/tmp/bin make]: exit code: 2
```

**Comment by MarkDPierce** [comment]
Looks like you are using the make file which checks which version of GO you have on your machine. 1.20 changed a few things and the make.common file doesnt look like its been configured for that.

Doing this by hand, so `docker build . --platform linux/amd64` worked fine.

**Comment by JetSquirrel** [comment]
Thank you very mush. 

I solved the problem by changing the compilation machine.
