### ISSUE TITLE
Gracefully handle issue description being too large.

### ISSUE THREAD

**Issue by bwplotka** [prometheus-community/jiralert#41]
We got that because we put too much stuff on the JIRA issue while creating. The limit was around 32k chars. I feel like we could do better in Jiralert to truncate the description automatically if too large?

Want to start a discussion on it (:

**Comment by ianbillett** [comment]
There is a limit of 32,767 characters in Jira Cloud ([source](https://jira.atlassian.com/browse/JRASERVER-64351))

**Comment by bumarcell** [comment]
Did it happen? :D

**Comment by bwplotka** [comment]
Nope, help wanted.

**Comment by gerrywd** [comment]
> Nope, help wanted.

@bwplotka Does this PR help or do you have any feedback for the author?
https://github.com/prometheus-community/jiralert/pull/165

**Comment by bwplotka** [comment]
Thanks for ping 💪🏽 It indeed helped

**Comment by gerrywd** [comment]
Thank you for your time @bwplotka.

If you have a little time to spare. There are also PRs for:
https://github.com/prometheus-community/jiralert/issues/152 (help also requested there)
https://github.com/prometheus-community/jiralert/issues/159
https://github.com/prometheus-community/jiralert/pull/161 (two alternative PRs there)
