### ISSUE TITLE
Log files?

### ISSUE THREAD

**Issue by bumarcell** [prometheus-community/jiralert#89]
Hi,
I was trying to find the log file for jiralert. Looked into /var/log/ but didnt find any related logs.

Are logs written to a file in Jiralert and if yes, where can I find it?
Thanx :-)

**Comment by erdii** [comment]
Hey @bumarcell :)

jiralert does not write any logfiles, it sends all it's outputs to stdout/stderr.
This means that the surrounding superrvisor system that starts jiralert, is responsible for collecting jiralert logs.

For example, if you run jiralert via systemd: https://unix.stackexchange.com/questions/20399/view-stdout-stderr-of-systemd-service

**Comment by bumarcell** [comment]
Ok got it
Thanx a lot!
